api:
  devolucao:
    dias: 5
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/safeAPI
    username: safeapi
    password: safeapi
  jpa:
    hibernate:
      ddl-auto: validate
  mail:
      host: smtp.gmail.com
      port: 587
      username: seuemail@email.com
      password: suasenha
      protocol: smtp
      tls: true
      properties.mail.smtp:
        auth: true
        starttls.enable: true
        ssl.trust: smtp.gmail.com
server:
  error:
    include-message: always
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
